name: Validate Kotlin Multiplatform

on:
  workflow_call:
    inputs:
      ref:
        description: 'The specific git commit SHA to checkout and test'
        required: true
        type: string

jobs:
  test-kotlin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      # Runs checks and tests for all targets (JVM, JS/TS, Native metadata)
      - name: Run Gradle Checks
        run: ./gradlew check --no-daemon
